export default {
  'pages/idolForums/idolForums': '战姬众（论坛）主tab',
  'pages/index/index': '动态 主tab',
  'pages/user/index': '个人中心 主tab',
  'pages/events/events': '活动列表 主tab',
  'pages/idols-intro/idols-intro': '歌姬介绍 主tab',
  'pages/idsol-intro-copy/idols-intro': '歌姬介绍',
  'pages/forumView/index': '主贴详情 战姬众的贴子点进去',
  'pages/task/index': '应援任务列表 战姬众和歌姬介绍有入口',
  'pages/taskRules/index': '应援秘籍 应援任务列表 → 创作任务 → 应援秘籍',
  'pages/videoView/index': '视频播放页 活动列表有入口',
  'pages/editForum/index': '发贴页面 战姬众右下角发帖按钮',
  'pages/leaderBoard/index': '榜单页面 老页面',
  'pages/userContribution/index': '用户贡献 老页面',
  'pages/newsView/index': '普通博文详情 活动列表页有入口',
  'pages/fansLeaderBoard/index': '歌姬周榜总榜',
  'pages/commentView/index': '评论详情页面',
  'pages/userCollection/index': '我的收藏',
  'pages/msgView/index': '通知详情 个人中心 → 消息 → 通知',
  'pages/replyComment/index': '回复评论',
  'pages/announcementView/index': '公告详情 战姬众 → 发帖 → 底部条目',
  'pages/agreement/index': '发帖协议',
  'pages/accountBind/accountBind': '用户绑定 编辑用户信息 → 用户绑定',
  'pages/viewBindGuide/viewBindGuide': '绑定教程',
  'pages/editUserInfo/index': '编辑用户信息',
  'pages/editUserInfo/upload/upload': '上传头像（剪裁）',
  'pages/editUserInfo/input-page/input-page': '修改签名、昵称',
  'pages/my-fans/my-fans': '我的粉丝',
  'pages/it-main-page/it-main-page': '其他用户的个人主页',
  'pages/avatar-mange/avatar-mange': '佩戴头像挂件',
  'pages/my-medal/my-medal': '我的徽章',
  'pages/my-wallet/my-wallet': '我的钱包',
  'pages/my-storage/my-storage': '我的储藏箱',
  'pages/my-message/my-message': '我的消息',
  'pages/event/top/top': '复活活动',
  'pages/event/rewards/rewards': '复活活动',
  'pages/event/rank/rank': '复活活动',
  'pages/event/progress/progress': '复活活动',
  'pages/event/sendGift/sendGift': '复活活动',
  'pages/event/idolTalk/idolTalk': '复活活动',
  'pages/event/distributePoint/distributePoin': '复活活动',
  'pages/event-vote/vote': '投票活动',
  'pages/event-vote/rank/rank': '投票活动',
  'pages/event-vote/vote2/vote2': '(活动)红白之战、票选锦鲤姬',
  'pages/lottery/lottery/lottery': '(抽奖)票选锦鲤姬',
  'pages/lottery/record/record': '(抽奖)票选锦鲤姬',
  'pages/lottery/address/address': '(抽奖)票选锦鲤姬',
  'pages/scan-code/checkin/checkin': '(扫码)签到、兑换、萤火虫线下活动',
  'pages/scan-code/error/error': '(扫码)签到、兑换、萤火虫线下活动',
  'pages/scan-code/exchange/exchange': '(扫码)签到、兑换、萤火虫线下活动',
  'pages/event-checkin/event-checkin': '(扫码)签到、兑换、萤火虫线下活动',
  'pages/liveVoting/index': 'BML 星夺战活动',
  'pages/event-racing/index': 'BML 星夺战活动',
  'pages/event-racing/rank/rank': 'BML 星夺战活动',
  'pages/event-summer/event-summer': '夏日祭活动',
  'pages/event-summer/video/video': '夏日祭活动',
  'pages/event-summer/event-summer-second/event-summer-second': '夏日祭活动'
}
